### ISSUE TITLE
version tags missing?

### ISSUE THREAD

**Issue by csantanapr** [NatzkaLabsOpenSource/managed-kubernetes#9]
Great repo, very useful at least for me learning crossplane.

In the readme it mentions versions like `3.0` `3.1` and `3.2` but I don't find any tags on the repos.
Would be possible to create tags to keep track, and easier way to see changes from version to version?

**Comment by ghost** [comment]
Added Tag and Release v1.1. I will create those for any coming versions. Thanks a lot for this issue.
